import {Mobile} from './app/shared/models/Mobile';
import { Tag } from './app/shared/models/Tag';
export const sample_mobile: Mobile[] = [
  {
    id: '1',
    name: 'Iphone 15',
    Description: '15.54 cm(6.1") Super Retina XDR Display',
    price: 85000,
    favorite: true,
    Specification: ['Smoke White', '5G', 'IOS'],
    stars: 4.5,
    imageUrl: './assets/Iphone 15jpg.jpg',
    tags: ['New Arrived', 'Iphone', 'Best Selling'],
  },
  {
    id: '2',
    name: 'Samsung Galaxy s20 FE',
    price: 36000,
    Description: '16.0 cm (6.3") Super Retina XDR Display',
    favorite: true,
    Specification: ['CloudNavy', '5G', 'Android'],
    stars: 4.7,
    imageUrl: './assets/Samsung Galaxy s20.jpg',
    tags: ['Samsung', 'Best Selling'],
  },
  {
    id: '3',
    name: 'One Plus Node 3',
    price: 55000,
    Description: '15.54 cm(6.1") Super Retina XDR Display',
    favorite: false,
    Specification: ['Mist Green', '5G', 'Android'],
    stars: 3.5,
    imageUrl: './assets/OnePlus Node3.jpg',
    tags: ['OnePlus', 'Best Selling', 'New Arrival'],
  },
  {
    id: '4',
    name: 'Vivo v27',
    price: 32800,
    Description: '15.54 cm(6.1") Super Retina XDR Display',
    favorite: true,
    Specification: ['Magic Blue', '5G', 'Android'],
    stars: 3.3,
    imageUrl: './assets/Vivo v27.jpg',
    tags: ['Vivo', 'New Arrival'],
  },
  {
    id: '5',
    name: 'Realme 11x',
    price: 15039,
    Description: '15.54 cm(6.1") Super Retina XDR Display',
    favorite: false,
    Specification: ['Midnight Black', '5G', 'Android'],
    stars: 3.0,
    imageUrl: './assets/realme 11x.jpg',
    tags: ['Realme', 'Best Selling'],
  },
  {
    id: '6',
    name: 'Iphone 14',
    price: 70000,
    Description: '15.54 cm(6.1") Super Retina XDR Display',
    favorite: false,
    Specification: ['Smoke White', '5G', 'IOS'],
    stars: 4.0,
    imageUrl: './assets/iphone 14.jpg',
    tags: ['Iphone', 'Best Selling'],
  },
  {
    id: '7',
    name: 'One Plus Node CE 3',
    price: 19000,
    Description: '15.54 cm(6.1") Super Retina XDR Display',
    favorite: false,
    Specification: ['Black', '5G', 'Android'],
    stars: 3.2,
    imageUrl: './assets/One Plus Node cE 3.jpg',
    tags: ['OnePlus'],
  },
  {
    id: '8',
    name: 'Samsung Galaxy M14',
    price: 25000,
    Description: '15.54 cm(6.1") Super Retina XDR Display',
    favorite: true,
    Specification: ['White', '5G', 'Android'],
    stars: 3.9,
    imageUrl: './assets/Samsung Galay m14.jpg',
    tags: ['Samsung'],
  },
  {
    id: '9',
    name: 'Iphone 13',
    price: 60000,
    Description: '15.54 cm(6.1") Super Retina XDR Display',
    favorite: true,
    Specification: ['Mist Green', '5G', 'IOS'],
    stars: 4.0,
    imageUrl: './assets/Iphone 13.jpg',
    tags: ['Iphone', 'Best Selling'],
  },
];

export const sample_tags: Tag[] = [
  { name: 'All', count: 9 },
  { name: 'Iphone', count: 3 },
  { name: 'Samsung', count: 2 },
  { name: 'OnePlus', count: 2 },
  { name: 'Realme', count: 1 },
  { name: 'Vivo', count: 1 },
  { name: 'Best Selling', count: 6 },
  { name: 'New Arrival', count: 3 },
];
